//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.OrderAssignment = new HashSet<OrderAssignment>();
        }
    
        public int EquipmentId { get; set; }
        public string Name { get; set; }
        public string InventoryNo { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<OrderAssignment> OrderAssignment { get; set; }
    }
}
