//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.MaterialStock = new HashSet<MaterialStock>();
            this.OrderMaterial = new HashSet<OrderMaterial>();
            this.PurchaseItem = new HashSet<PurchaseItem>();
        }
    
        public int MaterialId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public decimal MinQty { get; set; }
    
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual ICollection<MaterialStock> MaterialStock { get; set; }
        public virtual ICollection<OrderMaterial> OrderMaterial { get; set; }
        public virtual ICollection<PurchaseItem> PurchaseItem { get; set; }
    }
}
