//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterial
    {
        public int OrderMaterialId { get; set; }
        public int ProductionOrderId { get; set; }
        public int MaterialId { get; set; }
        public decimal RequiredQty { get; set; }
        public decimal IssuedQty { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
