//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public int OrderAssignmentId { get; set; }
        public int ProductionOrderId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
