//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        public ProductionOrder()
        {
            this.OrderAssignment = new HashSet<OrderAssignment>();
            this.OrderMaterial = new HashSet<OrderMaterial>();
        }
    
        public int ProductionOrderId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignment { get; set; }
        public virtual ICollection<OrderMaterial> OrderMaterial { get; set; }
        public virtual Product Product { get; set; }
    }
}
