//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseItem = new HashSet<PurchaseItem>();
        }
    
        public int PurchaseId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchaseItem> PurchaseItem { get; set; }
    }
}
